.PHONY: all
all:
	cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=[path to vcpkg.cmake] -DCMAKE_EXPORT_COMPILE_COMMANDS=1
	cmake --build build

.PHONY: run
run:
	./build/courses/PV112/PlanetGL/PV112_project_template

.PHONY: clean
clean:
	rm -rf ./build

